CREATE TABLE PUBLIC.APPLICATION (
	ID_APPLICATION INTEGER NOT NULL,
	NAME VARCHAR(25),
	NATIVE VARCHAR(25),
	PRIMARY KEY (ID_APPLICATION)
);
CREATE TABLE PUBLIC.CONFIGURATION (
	ID_PROFILE INTEGER,
	ID_APPLICATION INTEGER,
	POSITION VARCHAR(25),
	ACTIVE VARCHAR(25)
);
CREATE TABLE PUBLIC.PROFILE (
	ID_PROFILE INTEGER NOT NULL,
	NAME VARCHAR(30),
	PRIMARY KEY (ID_PROFILE)
);
INSERT INTO PUBLIC.APPLICATION(ID_APPLICATION, NAME, NATIVE) VALUES (1, 'Clock', 'True');
INSERT INTO PUBLIC.CONFIGURATION(ID_PROFILE, ID_APPLICATION, "POSITION", ACTIVE) VALUES (1, 1, '500.1000', 'True');
INSERT INTO PUBLIC.PROFILE(ID_PROFILE, NAME) VALUES (1, 'Default');
